name: Branch Protection Setup

on:
  workflow_dispatch:

jobs:
  setup-protection:
    name: Setup Branch Protection
    runs-on: ubuntu-latest

    steps:
      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            const { data: branches } = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const mainBranch = branches.find(branch => 
              branch.name === 'main' || branch.name === 'master'
            );

            if (mainBranch) {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: mainBranch.name,
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'validate_package'
                  ]
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false
                },
                restrictions: {
                  users: [context.repo.owner],
                  teams: []
                },
                allow_force_pushes: false,
                allow_deletions: false
              });
              
              console.log(`Branch protection enabled for ${mainBranch.name}`);
              console.log(`Only ${context.repo.owner} can merge pull requests`);
            } else {
              console.log('No main/master branch found');
            }
