name: Pull Request Validation

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  validate_package:
    name: Validate Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Check formatting
        run: dart format --set-exit-if-changed .
